name: Run KofiuMonitor on Weekdays Only

on:
  schedule:
    - cron: '0 0 * * 1-5'  # 매주 월~금 오전 9시 (KST 기준)
  workflow_dispatch:       # 수동 실행도 가능

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn compile

    - name: Run KofiuPdfMonitor
      run: mvn exec:java -Dexec.mainClass="com.example.kofiu.KofiuPdfMonitor"
      env:
        NAVER_USER: ${{ secrets.NAVER_USER }}
        NAVER_PASS: ${{ secrets.NAVER_PASS }}

    - name: Configure Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Conditionally commit & push last_version.txt
      run: |
        git pull
        if [ -f "last_version.txt" ]; then
          git add last_version.txt
          git commit -m "Update last_version.txt [skip ci]" || echo "No changes to commit"
          git push
        else
          echo "⚠️ last_version.txt 파일이 존재하지 않아 커밋 생략됨"
        fi
